### ISSUE TITLE
django createsuperuser command fails

### ISSUE THREAD

**Issue by mertsalik** [ITURO/ituro#59]
In order to create super user im running 
`python manage.py createsuperuser `
and getting this error

> Traceback (most recent call last):
>   File "ituro/manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
>     utility.execute()
>   File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 330, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/Library/Python/2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 50, in execute
>     return super(Command, self).execute(*args, **options)
>   File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 444, in execute
>     output = self.handle(*args, **options)
>   File "/Library/Python/2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 149, in handle
>     self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
>   File "/Users/mertsalik/Documents/School/ituro/ituro/accounts/models.py", line 30, in create_superuser
>     return self._create_user(email, password, True, True, **extra_fields)
>   File "/Users/mertsalik/Documents/School/ituro/ituro/accounts/models.py", line 23, in _create_user
>     user.save(using=self._db)
>   File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
>     force_update=force_update, update_fields=update_fields)
>   File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 738, in save_base
>     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
>   File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 822, in _save_table
>     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
>   File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
>     using=using, raw=raw)
>   File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 920, in _insert
>     return query.get_compiler(using=using).execute_sql(return_id)
>   File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
>     cursor.execute(sql, params)
>   File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 79, in execute
>     return super(CursorDebugWrapper, self).execute(sql, params)
>   File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/Library/Python/2.7/site-packages/django/db/utils.py", line 97, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/Library/Python/2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
>     return Database.Cursor.execute(self, query, params)
> django.db.utils.IntegrityError: NOT NULL constraint failed: accounts_customuser.last_login
> 

I think last_login field is missing in 
```
class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, is_staff, is_superuser,
                     **extra_fields):
```
We can fix this by giving last_login as a parameter to custom user model instance while creation.

**Comment by mertsalik** [comment]
And you can assign me to this issue. I'm trying to fresh install and run the entire project. 👊

**Comment by ilkerkesen** [comment]
That's interesting. @alperkesen how did you initiate the project this year? Maybe it's just version related or something like that. By the way, it would be great if we update README.md based on your new fresh installation.
